import json
import logging
from pathlib import Path
from typing import List, Dict, Any, Optional
from collections import defaultdict

logger = logging.getLogger(__name__)

class MitreMapper:
    def __init__(self, techniques_path: str):
        self.techniques_path = techniques_path
        self.techniques = {}
        self._load_techniques()

    def _load_techniques(self) -> None:
        path = Path(self.techniques_path)
        if not path.exists():
            logger.warning(f"MITRE techniques file not found: {self.techniques_path}")
            return
            
        try:
            with open(path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                self.techniques = data.get('techniques', {})
            logger.info(f"Loaded {len(self.techniques)} MITRE ATT&CK techniques.")
        except Exception as e:
            logger.error(f"Error loading MITRE techniques: {e}")

    def map_technique(self, technique_id: str) -> Optional[Dict[str, Any]]:
        if not technique_id:
            return None
            
        # Handle subtechniques (e.g. T1059.001)
        base_tech = technique_id.split('.')[0]
        
        if base_tech in self.techniques:
            tech_info = dict(self.techniques[base_tech])
            tech_info['id'] = base_tech
            
            if '.' in technique_id and 'subtechniques' in tech_info:
                sub_info = tech_info['subtechniques'].get(technique_id)
                if sub_info:
                    tech_info['name'] = f"{tech_info['name']}: {sub_info['name']}"
                    tech_info['description'] = sub_info.get('description', tech_info['description'])
                    tech_info['id'] = technique_id
                    
            return tech_info
        return None

    def map_alert(self, alert: Dict[str, Any]) -> Dict[str, Any]:
        tech_id = alert.get('mitre_technique')
        if tech_id:
            mitre_info = self.map_technique(tech_id)
            if mitre_info:
                alert['mitre_info'] = mitre_info
                
        return alert

    def get_tactic_summary(self, alerts: List[Dict[str, Any]]) -> Dict[str, int]:
        summary = defaultdict(int)
        for alert in alerts:
            tech_id = alert.get('mitre_technique')
            if tech_id:
                tech = self.map_technique(tech_id)
                if tech:
                    tactic = tech.get('tactic')
                    if tactic:
                        summary[tactic] += 1
        return dict(summary)

    def get_technique_coverage(self, alerts: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        coverage = {}
        for alert in alerts:
            tech_id = alert.get('mitre_technique')
            if tech_id and tech_id not in coverage:
                tech = self.map_technique(tech_id)
                if tech:
                    coverage[tech_id] = tech
                    
        return list(coverage.values())

    def get_all_tactics(self) -> List[str]:
        tactics = set()
        for tech in self.techniques.values():
            if 'tactic' in tech:
                tactics.add(tech['tactic'])
        return list(tactics)

    def get_techniques_by_tactic(self, tactic: str) -> List[Dict[str, Any]]:
        results = []
        for tech_id, tech in self.techniques.items():
            if tech.get('tactic', '').lower() == tactic.lower():
                t = dict(tech)
                t['id'] = tech_id
                results.append(t)
        return results

    def export_navigator_layer(self, alerts: List[Dict[str, Any]]) -> Dict[str, Any]:
        layer = {
            "name": "LightEDR Detection Coverage",
            "versions": {
                "attack": "14",
                "navigator": "4.9",
                "layer": "4.4"
            },
            "domain": "enterprise-attack",
            "description": "Generated by LightEDR",
            "techniques": []
        }
        
        tech_scores = defaultdict(int)
        for alert in alerts:
            tech_id = alert.get('mitre_technique')
            if tech_id:
                # Navigator typically wants the base technique and subtechnique mapped
                tech_scores[tech_id] += 1
                
        for tech_id, score in tech_scores.items():
            layer["techniques"].append({
                "techniqueID": tech_id,
                "score": score,
                "color": "#ff6666" if score > 2 else "#ffb366" if score > 1 else "#ffff66",
                "comment": f"Detected {score} times"
            })
            
        return layer
